### ISSUE TITLE
Obsolte documentation for :affects-dirty-status-p

### ISSUE THREAD

**Issue by exot** [skypher/weblocks#44]
Commit df17f298293a3f20cc564b2ceaa359a9f87d7437 sets the defalt of `:affects-dirty-status-p` to `nil`, but the documentation of the slot still says that the default is `t`.  Can you please update this doc?

Thanks!

  Daniel

**Comment by html** [comment]
Fixed in https://github.com/skypher/weblocks/commit/c3720a38ed4e13f10b1350cf82fd9976c5370247
Is that all ?

**Comment by exot** [comment]
I had some trouble with gridedit not updating the view when adding new entries, but I see that you have made some changes which may fix this issue.  So, yes, that's all for now.

Thanks!

**Comment by html** [comment]
Thanks you too.
